#!/bin/bash

DEST=$1

CGO_ENABLED=${CGO_ENABLED:-1} CC=${CC:-gcc} GOOS=${GOOS:-linux} GOARCH=${GOARCH:-amd64} go build \
	-o "$DEST/docker-$VERSION" \
	"${BUILDFLAGS[@]}" \
	-ldflags "
		$LDFLAGS
		$LDFLAGS_STATIC_DOCKER
	" \
	./docker
echo "Created binary: $DEST/docker-$VERSION"

hash_files "$DEST/docker-$VERSION"
