#!/bin/bash

DEST=$1

# if we have our linux/amd64 version compiled, let's symlink it in
if [ -x "$DEST/../binary/docker-$VERSION" ]; then
  mkdir -p "$DEST/linux/amd64"
  (
  cd "$DEST/linux/amd64"
  ln -s ../../../binary/* ./
  )
  echo "Created symlinks:" "$DEST/linux/amd64/"*
fi

for platform in $DOCKER_CROSSPLATFORMS; do
  (
  mkdir -p "$DEST/$platform" # bundles/VERSION/cross/GOOS/GOARCH/docker-VERSION
  GOOS=${platform%/*}
  GOARCH=${platform##*/}
  case ${GOARCH} in
    arm)
      export CC=${GOARCH}-${GOOS}-gnueabihf-gcc
      export CGO_ENABLED=1
      export GOOS=linux
      export GOARCH=arm
      export  LDFLAGS="-extld=${CC} $LDFLAGS"
      ;;
    amd64)
      case ${GOOS} in
        linux)
          export CC=gcc
          export CGO_ENABLED=1
          ;;
        darwin)
          export CC=gcc
          export CGO_ENABLED=0
          export LDFLAGS_STATIC=""
          ;;
        esac
        ;;
      386)
        case ${GOOS} in
          darwin)
            export CC=gcc
            export CGO_ENABLED=0
            export LDFLAGS_STATIC=""
            ;;
           *)
            echo "${GOARCH}-${GOOS}"
        esac
        ;;
      *)
        echo "${GOARCH} not supported"
        ;;
  esac
  source "$(dirname "$BASH_SOURCE")/binary" "$DEST/$platform"
  )
done
